CREATE TABLE Role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state ENUM('ACTIVE', 'INACTIVE', 'DELETED') NOT NULL
);

CREATE TABLE User (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    identificationNumber VARCHAR(50) NOT NULL UNIQUE,
    role_id BIGINT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state ENUM('ACTIVE', 'INACTIVE', 'DELETED') NOT NULL,
    FOREIGN KEY (role_id) REFERENCES Role(id)
);

CREATE TABLE Client (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES User(id)
);

CREATE TABLE CreditApplication (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    amount DOUBLE NOT NULL,
    term INT NOT NULL,
    purpose VARCHAR(255),
    status ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED') NOT NULL,
    applicant_id BIGINT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (applicant_id) REFERENCES Client(id)
);

CREATE TABLE Document (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    documentType VARCHAR(100) NOT NULL,
    filePath VARCHAR(255) NOT NULL,
    creditApplication_id BIGINT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state ENUM('PENDING_REVIEW', 'APPROVED', 'REJECTED') NOT NULL,
    FOREIGN KEY (creditApplication_id) REFERENCES CreditApplication(id)
);

CREATE TABLE Notification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(255) NOT NULL,
    sentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    relatedApplication_id BIGINT,
    recipient_id BIGINT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (relatedApplication_id) REFERENCES CreditApplication(id),
    FOREIGN KEY (recipient_id) REFERENCES User(id)
);

CREATE TABLE AuditLog (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    performedBy BIGINT,
    FOREIGN KEY (performedBy) REFERENCES User(id)
);